# Generated by Django 5.1 on 2024-08-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_interests_remove_user_residence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='interest',
            new_name='interests',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='residence',
        ),
    ]
