# Generated by Django 5.1 on 2024-08-25 15:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_first_name_user_last_name_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_materials',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=5),
        ),
    ]
