# Generated by Django 5.1 on 2024-08-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_description_event_gender_event_interests_and_more'),
        ('user', '0003_rename_interest_user_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_events',
            field=models.ManyToManyField(related_name='users', to='events.event'),
        ),
    ]
