# Generated by Django 5.1 on 2024-08-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_registered_users'),
        ('user', '0004_user_registered_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registered_events',
            field=models.ManyToManyField(blank=True, related_name='registered_users', to='events.event'),
        ),
    ]
