# Generated by Django 5.1 on 2024-08-25 02:33

from django.db import migrations, models


def add_dummy_data(apps):
    Appointment = apps.get_model('appointments', 'Appointment')
    appointments = [
        {"type": "Consultation", "time": "10:00 AM", "details": "General health consultation"},
        {"type": "Dental Checkup", "time": "11:00 AM", "details": "Routine dental examination"},
        {"type": "Therapy Session", "time": "1:00 PM", "details": "Mental health therapy session"},
        {"type": "Eye Examination", "time": "2:30 PM", "details": "Comprehensive eye exam"},
        {"type": "Physical Therapy", "time": "4:00 PM", "details": "Physical therapy for back pain"}
    ]
    for appointment in appointments:
        Appointment.objects.create(**appointment)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('details', models.TextField()),
            ],
        ),
    migrations.RunPython(add_dummy_data),
    ]
