# Generated by Django 5.1 on 2024-08-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('user', '0003_rename_interest_user_interests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='registered_users',
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to='user.user'),
        ),
        migrations.AddField(
            model_name='event',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='user.user'),
        ),
        migrations.AddField(
            model_name='event',
            name='waitList',
            field=models.ManyToManyField(blank=True, related_name='waitlist', to='user.user'),
        ),
        migrations.AddField(
            model_name='event',
            name='required_modules',
            field=models.ManyToManyField(blank=True, to='events.module'),
        ),
    ]
