# Generated by Django 5.1 on 2024-08-24 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_description_event_gender_event_interests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registered_users',
        ),
    ]
