# Generated by Django 5.1 on 2024-08-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='interests',
            field=models.CharField(max_length=255),
        ),
    ]
