# Generated by Django 5.1 on 2024-08-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_id_event_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.AutoField(primary_key=True, default=None),
        ),
    ]
