# Generated by Django 5.1 on 2024-08-25 09:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='learning_materials',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
