# Generated by Django 5.1 on 2024-08-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='interests',
            field=models.CharField(max_length=255),
        ),
    ]
